;/DEP_PDF_SETUP /DUSER_LEVEL 

# 金山 PDF 自定义程序功能配置文件
# 雨糖科技 以爱敬献 - 梦想成真 生生不息

[Feature]
;sQD2Rt_mwGqKSU9I2xbCuDGc10=cQD2Rt_mwGqk99gTmjC7T-YR10
ZYTJwCQFjyrKSU9I2xbCuXrj10=ZYTJwCQFjyr4U3A385v-Nx9n10
xn3QfP-XIpyKSU9I2xbCubad10=hn3QfP-XIpyk99gTmjC7T6IF10
pDKIJxJrennKSU9I2xbCurSc10=pDKIJxJrennk99gTmjC7TE8V10

[Auth]
LicenseServerUrl=http://0.0.0.0/account

[Server]
IntranetPluginsAuthServer="http://plugin.plus.wpseco.cn/xva/"
IntranetPluginsICServer="http://0.0.0.0/xva/v1/plugin/stat"
QingUrl=http://0.0.0.0
CustomUpdateServer=http://0.0.0.0/wpsoffice/updateserver/update
CustomAutoNomInfoSvr=http://0.0.0.0/wpsoffice/wpscollect
InfoCollectServer=http://0.0.0.0/wpsv6internet/infos.ads
QInfoCollectServer=http://0.0.0.0/qingoffice/infos.ads

[Account]
CompanyCode=OFFLINEMODE
EnableSwitchOtherLoginType=false

[Support]
Support2016SN=true
Update=false
DisableUpdateCheck=true
IntranetVersion7=true
IntranetDrive=true
ForceIntranet=true
EnableNetwork=false
EnableCloudDocs=false
NotStartCloudSvrBroadcast=true
OnlineFeatures=false
IsDisableLoadCloudDocLib=true
DisableUpdateExternalDataLinkDialog=true
CloudDocOnline=false
SupportNewToCloud=false
EnableWPSOfficialWebsite=false
WeChatCustomerService=false
ShowWeChatQRCode=false
DisableMainResourceVerification=true
CloudLink=false
FileMenuDocumentHistory=false
FeedbackByMailInMenu=false
UseRoaming2015=false
FileRoamingShellContextMenu=false
EULAPopup=false
EnableAccount=false
WPS365ForceLogin=false
forbidEditInForceLogin=false
OemPackageLogin=true
QingForceLogin=false
QingShowLoginWindowOnStartup=false
DocPermission=false
EnterpriseDocpermission=false
EncryptWithoutAccount=true
EnableSecDocRightsList=false
HideRightlistForNonSecdoc=true
SupportDocAuthenticate=false
OnlineSecurityDocument=false
SaveasSecurityDocByAPI=false
SaveToSecurityDocDirectly=false
NeedPrivacyPolicyPopup=false
DisableGlobalInfoCollect=true
ReportAllInfoToDataWarehouse=false
CommandTriggerInfoCollect=false
GoogleAnalytics=false
IcibaWakeupInfoCollect=false
EnableSNInfoCollect=false
EnableProductIdentifierCollect=false
CollectAuthInfoOnStartup=false
IntranetPluginsAuthType=2
IntranetPluginsVersion=true
QingLoginOfflineMode=true
EnCldSvrOnEmbed=false
EnableOnlineFunction=false
DisalbeUpdateInfoCollect=true
UpdateSchdTaskByKsolaunch=false
DisableCollabration=true
FileRoamingShareLink=false
WPSCloudLogin=false
ReportGetIpAddress=false
DoNotSupportMessagePush=true
CloudStorage=false
DisableShareDocs=true
EnableClientCooperation=false
DisableMessagePush=true
HideCloudSpace=true
SupportCloudPushMsg=false
ShowCustomerServiceQR=false
isSupportDocCloudSync=false
DisableSNOverNumberLimit=true
ForbidEditInLoginSNAuth=false
DisableOnlineTemplateLibrary=true
DisableOnlineMaterialLibrary=true
OnlineAppcenter=false
OnlinePictures=false
WPSDriveEnabled=false
PDFAuthShowPrompt=true
DisableEbookRead=false
PDFOCRLocalization=true
