
[Setup]
LANG_ID=2052
build_version=12.8.0.15662
;ProductName=金山 PDF
ProductVersion=雨糖科技特别版
;StartMenuDir=WPS PDF 专业版
;InstExeCount=0
UninstExeCount=1
UninstActionFile=office6\cfgs\oeminfo\oem.exe
UninstActionParameter=/regfile=xiezai.reg
UninstActionWait=1
