;/DEP_PDF_SETUP /DUSER_LEVEL 

# 金山 PDF 自定义程序功能配置文件
# 雨糖科技 以爱敬献 - 梦想成真 生生不息

[Feature]
sQD2Rt_mwGqKSU9I2xbCuDGc10=cQD2Rt_mwGqk99gTmjC7T-YR10
ZYTJwCQFjyrKSU9I2xbCuXrj10=ZYTJwCQFjyr4U3A385v-Nx9n10
xn3QfP-XIpyKSU9I2xbCubad10=hn3QfP-XIpyk99gTmjC7T6IF10

[Server]
IntranetPluginsAuthServer="http://plugin.plus.wpseco.cn/xva/"
IntranetPluginsICServer="http://plugin.plus.wpseco.cn/xva/v1/plugin/stat"

[Support]
Support2016SN=true
DisableUpdateCheck=true
IntranetDrive=true
EnableCloudDocs=false
CloudDocOnline=false
XiuTang=false
DisableGlobalInfoCollect=true
CommandTriggerInfoCollect=false
GoogleAnalytics=false
QingLoginOfflineMode=true
IntranetPluginsAuthType=2
IntranetPluginsVersion=true
PDFAuthShowPrompt=true
DisableEbookRead=false
PDFOCRLocalization=True
